<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  1 => 
  array (
    'name' => 'Theme Dashboard',
    'package' => 'dashboard_theme',
    'version' => '2.4.0-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/dashboard',
  ),
  3 => 
  array (
    'package' => 'dashboard',
    'name' => 'dashboard',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/dashboard',
    'active' => 1,
  ),
);
